setwd("/Users/bevan/phd/QISharedFolder/ADCS2013Impact/analysis")
data = read.table("network_measures.txt", sep="\t", header=T)

pdf("../latex/figures/network_measures_a.pdf", width=5, height=4)
par(mar=c(4,4,0.2,4)+.1, mfrow=c(1,1)) 
plot(data$year, data$num_nodes, type="o", ylim=c(0,450), ylab="Number of Edges or Nodes", xaxt="n", xlab="Year")
axis(side=1, at=c(2000, 2003, 2006, 2009, 2012))
lines(data$year, data$num_edges, type="o", lty=2)
par(new=TRUE)
plot(data$year, data$num_edges/data$num_nodes, type="o", lty=3, xaxt="n", yaxt="n", xlab="", ylab="", col="red", ylim=c(0.3,1.7))
axis(4)
mtext("Edge to Node Ratio (E/N)", side=4, line=3)
legend("bottomright", pch=1, cex=0.85, bty="n", col=c("black", "black", "red"), legend=c("Number of Nodes", "Number of Edges", "Edge to Node Ratio"), lty=c(1,2,3))
dev.off()

pdf("../latex/figures/network_measures_b.pdf", width=5, height=4)
par(mar=c(4,4,0.2,4)+.1, mfrow=c(1,1))
plot(data$year, data$avg_path, ylim=c(1,5), lty=1, type="o", ylab="Average Path Length", xaxt="n", xlab="Year")
axis(side=1, at=c(2000, 2003, 2006, 2009, 2012))
par(new=TRUE)
plot(data$year, data$avg_clusco, type="o", lty=2, xaxt="n", yaxt="n", xlab="", ylab="", ylim=c(0.57, 0.68))
axis(4)
mtext("Clustering Coefficient", side=4, line=3)
legend("bottomright", pch=1, cex=0.85, bty="n", legend=c("Average Path Len.", "Clustering Coefficient"), lty=c(1,2))

dev.off()